// This file is auto-generated by @hey-api/openapi-ts

export const AcePoolAllStatsApiSchema = {
    properties: {
        pid: {
            type: 'integer',
            title: 'Pid'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AcePoolStat'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['pid', 'status'],
    title: 'AcePoolAllStatsApi',
    description: 'Model for all stats of AcePool instances.'
} as const;

export const AcePoolEntryForAPISchema = {
    properties: {
        locked_in: {
            type: 'boolean',
            title: 'Locked In',
            default: false
        },
        time_until_unlock: {
            type: 'integer',
            title: 'Time Until Unlock'
        },
        time_running: {
            type: 'integer',
            title: 'Time Running'
        },
        ace_pid: {
            type: 'integer',
            title: 'Ace Pid'
        },
        content_id: {
            type: 'string',
            title: 'Content Id'
        },
        last_used: {
            type: 'string',
            format: 'date-time',
            title: 'Last Used'
        },
        date_started: {
            type: 'string',
            format: 'date-time',
            title: 'Date Started'
        },
        ace_hls_m3u8_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ace Hls M3U8 Url'
        }
    },
    type: 'object',
    required: ['ace_pid', 'content_id', 'last_used', 'date_started'],
    title: 'AcePoolEntryForAPI',
    description: 'Nice model with some calculated fields for the API.'
} as const;

export const AcePoolForApiSchema = {
    properties: {
        ace_version: {
            type: 'string',
            title: 'Ace Version'
        },
        ace_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ace Address'
        },
        max_size: {
            type: 'integer',
            title: 'Max Size'
        },
        healthy: {
            type: 'boolean',
            title: 'Healthy'
        },
        transcode_audio: {
            type: 'boolean',
            title: 'Transcode Audio'
        },
        ace_instances: {
            items: {
                '$ref': '#/components/schemas/AcePoolEntryForAPI'
            },
            type: 'array',
            title: 'Ace Instances'
        },
        external_url: {
            type: 'string',
            title: 'External Url'
        }
    },
    type: 'object',
    required: ['ace_version', 'ace_address', 'max_size', 'healthy', 'transcode_audio', 'ace_instances', 'external_url'],
    title: 'AcePoolForApi',
    description: 'Model for the AcePool API response.'
} as const;

export const AcePoolStatSchema = {
    properties: {
        response: {
            '$ref': '#/components/schemas/AcePoolStatResponse'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['response'],
    title: 'AcePoolStat',
    description: 'Matches the stat response from the AcePool API.'
} as const;

export const AcePoolStatResponseSchema = {
    properties: {
        uploaded: {
            type: 'integer',
            title: 'Uploaded'
        },
        network_monitor_status: {
            type: 'integer',
            title: 'Network Monitor Status'
        },
        debug_level: {
            type: 'integer',
            title: 'Debug Level'
        },
        disk_cache_stats: {
            '$ref': '#/components/schemas/AcePoolStatResponseDiskCache'
        },
        speed_down: {
            type: 'integer',
            title: 'Speed Down'
        },
        speed_up: {
            type: 'integer',
            title: 'Speed Up'
        },
        network_monitor_started: {
            type: 'boolean',
            title: 'Network Monitor Started'
        },
        selected_stream_index: {
            type: 'integer',
            title: 'Selected Stream Index'
        },
        total_progress: {
            type: 'integer',
            title: 'Total Progress'
        },
        stream_status: {
            type: 'integer',
            title: 'Stream Status'
        },
        client_session_id: {
            type: 'integer',
            title: 'Client Session Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        downloaded: {
            type: 'integer',
            title: 'Downloaded'
        },
        manifest_access_mode: {
            type: 'integer',
            title: 'Manifest Access Mode'
        },
        peers: {
            type: 'integer',
            title: 'Peers'
        },
        playback_session_id: {
            type: 'string',
            title: 'Playback Session Id'
        },
        is_encrypted: {
            type: 'integer',
            title: 'Is Encrypted'
        },
        is_live: {
            type: 'integer',
            title: 'Is Live'
        },
        infohash: {
            type: 'string',
            title: 'Infohash'
        },
        selected_file_index: {
            type: 'integer',
            title: 'Selected File Index'
        },
        livepos: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AcePoolStatResponseLivePos'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['uploaded', 'network_monitor_status', 'debug_level', 'disk_cache_stats', 'speed_down', 'speed_up', 'network_monitor_started', 'selected_stream_index', 'total_progress', 'stream_status', 'client_session_id', 'status', 'downloaded', 'manifest_access_mode', 'peers', 'playback_session_id', 'is_encrypted', 'is_live', 'infohash', 'selected_file_index'],
    title: 'AcePoolStatResponse',
    description: 'Matches the response from the AcePool API.'
} as const;

export const AcePoolStatResponseDiskCacheSchema = {
    properties: {
        avail: {
            type: 'integer',
            title: 'Avail'
        },
        disk_cache_limit: {
            type: 'integer',
            title: 'Disk Cache Limit'
        },
        inactive_inuse: {
            type: 'integer',
            title: 'Inactive Inuse'
        },
        active_inuse: {
            type: 'integer',
            title: 'Active Inuse'
        }
    },
    type: 'object',
    required: ['avail', 'disk_cache_limit', 'inactive_inuse', 'active_inuse'],
    title: 'AcePoolStatResponseDiskCache',
    description: 'Matches the disk cache response from the AcePool API.'
} as const;

export const AcePoolStatResponseLivePosSchema = {
    properties: {
        last: {
            type: 'integer',
            title: 'Last'
        },
        live_first: {
            type: 'integer',
            title: 'Live First'
        },
        pos: {
            type: 'integer',
            title: 'Pos'
        },
        first_ts: {
            type: 'integer',
            title: 'First Ts'
        },
        last_ts: {
            type: 'integer',
            title: 'Last Ts'
        },
        is_live: {
            type: 'integer',
            title: 'Is Live'
        },
        live_last: {
            type: 'integer',
            title: 'Live Last'
        },
        buffer_pieces: {
            type: 'integer',
            title: 'Buffer Pieces'
        }
    },
    type: 'object',
    required: ['last', 'live_first', 'pos', 'first_ts', 'last_ts', 'is_live', 'live_last', 'buffer_pieces'],
    title: 'AcePoolStatResponseLivePos',
    description: 'Matches the live position response from the AcePool API.'
} as const;

export const AceScraperSourceApiSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        url: {
            type: 'string',
            maxLength: 2083,
            minLength: 1,
            format: 'uri',
            title: 'Url'
        },
        title_filter: {
            '$ref': '#/components/schemas/TitleFilter',
            default: {
                always_exclude_words: [],
                always_include_words: [],
                exclude_words: [],
                include_words: [],
                regex_postprocessing: []
            }
        },
        html_filter: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/HTMLScraperFilter'
                },
                {
                    type: 'null'
                }
            ]
        },
        type: {
            type: 'string',
            enum: ['html', 'iptv', 'api'],
            title: 'Type'
        }
    },
    type: 'object',
    required: ['name', 'url', 'type'],
    title: 'AceScraperSourceApi',
    description: 'Represent a scraper instance, generic for HTML and IPTV sources.'
} as const;

export const Body_Login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_Login-login_access_token'
} as const;

export const EPGApiHandlerHealthResponseSchema = {
    properties: {
        time_until_next_update: {
            type: 'integer',
            title: 'Time Until Next Update'
        },
        tvg_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tvg Ids'
        },
        epgs: {
            items: {
                '$ref': '#/components/schemas/EPGApiHealthResponse'
            },
            type: 'array',
            title: 'Epgs'
        }
    },
    type: 'object',
    required: ['time_until_next_update', 'tvg_ids', 'epgs'],
    title: 'EPGApiHandlerHealthResponse',
    description: 'Model for EPG API handler response.'
} as const;

export const EPGApiHealthResponseSchema = {
    properties: {
        url: {
            type: 'string',
            maxLength: 2083,
            minLength: 1,
            format: 'uri',
            title: 'Url'
        },
        overrides: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Overrides'
        },
        time_since_last_updated: {
            type: 'integer',
            title: 'Time Since Last Updated'
        },
        time_until_next_update: {
            type: 'integer',
            title: 'Time Until Next Update'
        }
    },
    type: 'object',
    required: ['url', 'overrides', 'time_since_last_updated', 'time_until_next_update'],
    title: 'EPGApiHealthResponse',
    description: 'Model for EPG API response.'
} as const;

export const EPGInstanceConf_InputSchema = {
    properties: {
        format: {
            type: 'string',
            enum: ['xml.gz', 'xml'],
            title: 'Format',
            default: 'xml.gz'
        },
        url: {
            type: 'string',
            maxLength: 2083,
            minLength: 1,
            format: 'uri',
            title: 'Url'
        },
        tvg_id_overrides: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Tvg Id Overrides',
            default: {}
        }
    },
    type: 'object',
    required: ['url'],
    title: 'EPGInstanceConf',
    description: `EPG (Electronic Program Guide) configuration definition.

tvg_id_overrides is a str:str dict where you can override stream tvg_ids to match those in the EPG.`
} as const;

export const EPGInstanceConf_OutputSchema = {
    properties: {
        format: {
            type: 'string',
            enum: ['xml.gz', 'xml'],
            title: 'Format',
            default: 'xml.gz'
        },
        url: {
            type: 'string',
            maxLength: 2083,
            minLength: 1,
            format: 'uri',
            title: 'Url'
        },
        tvg_id_overrides: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Tvg Id Overrides',
            default: {}
        },
        slug: {
            type: 'string',
            title: 'Slug',
            description: 'Generate a slug from the url.',
            readOnly: true
        }
    },
    type: 'object',
    required: ['url', 'slug'],
    title: 'EPGInstanceConf',
    description: `EPG (Electronic Program Guide) configuration definition.

tvg_id_overrides is a str:str dict where you can override stream tvg_ids to match those in the EPG.`
} as const;

export const ErrorDetailsSchema = {
    properties: {
        type: {
            type: 'string',
            title: 'Type'
        },
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'integer'
                    },
                    {
                        type: 'string'
                    }
                ]
            },
            type: 'array',
            title: 'Loc'
        },
        msg: {
            type: 'string',
            title: 'Msg'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            additionalProperties: true,
            type: 'object',
            title: 'Ctx'
        },
        url: {
            type: 'string',
            title: 'Url'
        }
    },
    type: 'object',
    required: ['type', 'loc', 'msg', 'input'],
    title: 'ErrorDetails'
} as const;

export const FoundAceStreamAPISchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        content_id: {
            type: 'string',
            title: 'Content Id'
        },
        infohash: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Infohash'
        },
        tvg_id: {
            type: 'string',
            title: 'Tvg Id'
        },
        tvg_logo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tvg Logo'
        },
        last_scraped_time: {
            type: 'string',
            format: 'date-time',
            title: 'Last Scraped Time'
        },
        program_title: {
            type: 'string',
            title: 'Program Title'
        },
        program_description: {
            type: 'string',
            title: 'Program Description'
        },
        quality: {
            type: 'integer',
            title: 'Quality'
        },
        has_ever_worked: {
            type: 'boolean',
            title: 'Has Ever Worked'
        },
        m3u_failures: {
            type: 'integer',
            title: 'M3U Failures'
        }
    },
    type: 'object',
    required: ['title', 'content_id', 'tvg_id', 'last_scraped_time', 'program_title', 'program_description', 'quality', 'has_ever_worked', 'm3u_failures'],
    title: 'FoundAceStreamAPI',
    description: 'Model for a found AceStream.'
} as const;

export const HTMLScraperFilterSchema = {
    properties: {
        target_class: {
            type: 'string',
            title: 'Target Class',
            default: ''
        },
        check_sibling: {
            type: 'boolean',
            title: 'Check Sibling',
            default: false
        }
    },
    type: 'object',
    title: 'HTMLScraperFilter',
    description: 'Model for HTML scraper filtering.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseModelSchema = {
    properties: {
        version: {
            type: 'string',
            title: 'Version'
        },
        version_full: {
            type: 'string',
            title: 'Version Full'
        },
        time_zone: {
            type: 'string',
            title: 'Time Zone'
        },
        threads: {
            items: {
                '$ref': '#/components/schemas/ThreadHealthModel'
            },
            type: 'array',
            title: 'Threads'
        },
        memory_usage_mb: {
            type: 'string',
            title: 'Memory Usage Mb'
        }
    },
    type: 'object',
    required: ['version', 'version_full', 'time_zone', 'threads', 'memory_usage_mb'],
    title: 'HealthResponseModel'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MessageResponseModelSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        errors: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    items: {
                        '$ref': '#/components/schemas/ErrorDetails'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Errors'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'MessageResponseModel',
    description: 'Generic API response message model.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['username', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const QualitySchema = {
    properties: {
        quality: {
            type: 'integer',
            title: 'Quality',
            default: -1
        },
        has_ever_worked: {
            type: 'boolean',
            title: 'Has Ever Worked',
            default: false
        },
        m3u_failures: {
            type: 'integer',
            title: 'M3U Failures',
            default: 0
        },
        last_message: {
            type: 'string',
            title: 'Last Message',
            default: ''
        }
    },
    type: 'object',
    title: 'Quality',
    description: 'Model for tracking quality of a stream.'
} as const;

export const StreamTokenSchema = {
    properties: {
        stream_token: {
            type: 'string',
            title: 'Stream Token'
        }
    },
    type: 'object',
    required: ['stream_token'],
    title: 'StreamToken'
} as const;

export const TVGEPGMappingsResponseSchema = {
    additionalProperties: {
        anyOf: [
            {
                type: 'string',
                maxLength: 2083,
                minLength: 1,
                format: 'uri'
            },
            {
                type: 'null'
            }
        ]
    },
    type: 'object',
    title: 'TVGEPGMappingsResponse',
    description: 'Model for TVG EPG mappings response.'
} as const;

export const ThreadHealthModelSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        is_alive: {
            type: 'boolean',
            title: 'Is Alive'
        }
    },
    type: 'object',
    required: ['name', 'is_alive'],
    title: 'ThreadHealthModel'
} as const;

export const TitleFilterSchema = {
    properties: {
        always_exclude_words: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Always Exclude Words',
            default: []
        },
        always_include_words: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Always Include Words',
            default: []
        },
        exclude_words: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Exclude Words',
            default: []
        },
        include_words: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Include Words',
            default: []
        },
        regex_postprocessing: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Regex Postprocessing',
            default: []
        }
    },
    type: 'object',
    title: 'TitleFilter',
    description: `Model for title filtering.

Items in regex_postprocessing will be applied to remove parts of the title via re.sub.

The other lists will be evaluated in order:
- always_exclude_words
- always_include_words
- exclude_words
- include_words (if populated, otherwise allow any)`
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        stream_token: {
            type: 'string',
            maxLength: 64,
            title: 'Stream Token'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        stream_token: {
            type: 'string',
            maxLength: 64,
            title: 'Stream Token'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['username', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            title: 'Username'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        stream_token: {
            type: 'string',
            maxLength: 64,
            title: 'Stream Token'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;