// This file is auto-generated by @hey-api/openapi-ts

/**
 * Model for all stats of AcePool instances.
 */
export type AcePoolAllStatsApi = {
    pid: number;
    status: (AcePoolStat | null);
};

/**
 * Nice model with some calculated fields for the API.
 */
export type AcePoolEntryForAPI = {
    locked_in?: boolean;
    time_until_unlock?: number;
    time_running?: number;
    ace_pid: number;
    content_id: string;
    last_used: string;
    date_started: string;
    ace_hls_m3u8_url?: (string | null);
};

/**
 * Model for the AcePool API response.
 */
export type AcePoolForApi = {
    ace_version: (AceVersionResult | null);
    ace_address: (string | null);
    max_size: number;
    healthy: boolean;
    transcode_audio: boolean;
    ace_instances: Array<AcePoolEntryForAPI>;
    external_url: string;
};

/**
 * Matches the stat response from the AcePool API.
 */
export type AcePoolStat = {
    response: AcePoolStatResponse;
    error?: (string | null);
};

/**
 * Matches the response from the AcePool API.
 */
export type AcePoolStatResponse = {
    uploaded: number;
    network_monitor_status: number;
    debug_level: number;
    disk_cache_stats: AcePoolStatResponseDiskCache;
    speed_down: number;
    speed_up: number;
    network_monitor_started: boolean;
    selected_stream_index: number;
    total_progress: number;
    stream_status: number;
    client_session_id: number;
    status: string;
    downloaded: number;
    manifest_access_mode: number;
    peers: number;
    playback_session_id: string;
    is_encrypted: number;
    is_live: number;
    infohash: string;
    selected_file_index: number;
    livepos?: (AcePoolStatResponseLivePos | null);
};

/**
 * Matches the disk cache response from the AcePool API.
 */
export type AcePoolStatResponseDiskCache = {
    avail: number;
    disk_cache_limit: number;
    inactive_inuse: number;
    active_inuse: number;
};

/**
 * Matches the live position response from the AcePool API.
 */
export type AcePoolStatResponseLivePos = {
    last: number;
    live_first: number;
    pos: number;
    first_ts: number;
    last_ts: number;
    is_live: number;
    live_last: number;
    buffer_pieces: number;
};

/**
 * Settings for scraping AceStreams.
 */
export type AceScrapeConf = {
    playlist_name?: string;
    adhoc_playlist_external_url?: (string | null);
    tvg_logo_external_url?: (string | null);
    html?: Array<ScrapeSiteHTML>;
    iptv_m3u8?: Array<ScrapeSiteIPTV>;
    api?: Array<ScrapeSiteAPI>;
    content_id_infohash_name_overrides?: {
        [key: string]: (string);
    };
    category_mapping?: {
        [key: string]: Array<(string)>;
    };
};

/**
 * Represent a scraper instance, generic for HTML and IPTV sources.
 */
export type AceScraperSourceApi = {
    name: string;
    url: string;
    title_filter?: TitleFilter;
    html_filter?: (HTMLScraperFilter | null);
    type: 'html' | 'iptv' | 'api';
};

export type type = 'html' | 'iptv' | 'api';

export type AceVersionResult = {
    code: number;
    version: string;
    platform: 'win32' | 'linux' | 'android';
};

export type platform = 'win32' | 'linux' | 'android';

export type ConfigExport = {
    scraper: AceScrapeConf;
};

export type ErrorDetails = {
    type: string;
    loc: Array<(number | string)>;
    msg: string;
    input: unknown;
    ctx?: {
        [key: string]: unknown;
    };
    url?: string;
};

/**
 * Model for a found AceStream.
 */
export type FoundAceStreamAPI = {
    title: string;
    content_id: string;
    infohash?: (string | null);
    tvg_id: string;
    tvg_logo?: (string | null);
    last_scraped_time: string;
    quality: number;
    has_ever_worked: boolean;
    m3u_failures: number;
};

export type HealthResponseModel = {
    version: string;
    version_full: string;
    time_zone: string;
    threads: Array<ThreadHealthModel>;
    memory_usage_mb: string;
};

/**
 * Model for HTML scraper filtering.
 */
export type HTMLScraperFilter = {
    target_class?: string;
    check_sibling?: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Model for a manually added AceStream.
 */
export type ManuallyAddedAceStream = {
    title: string;
    content_id: string;
    group_title: string;
};

/**
 * Generic API response message model.
 */
export type MessageResponseModel = {
    message: string;
    errors?: (Array<(string)> | Array<ErrorDetails> | null);
};

export type RemoteSettingsURLGetModel = {
    url: (string | null);
    status: string;
    last_fetched: (string | null);
};

export type RemoteSettingsURLSetModel = {
    url: (string | null);
};

/**
 * Scraper for API Sites.
 */
export type ScrapeSiteAPI = {
    type?: "api";
    name: string;
    url: string;
    title_filter?: TitleFilter;
};

/**
 * Model for a site to scrape.
 */
export type ScrapeSiteHTML = {
    type?: "html";
    name: string;
    url: string;
    title_filter?: TitleFilter;
    html_filter?: HTMLScraperFilter;
};

/**
 * Scraper for IPTV Sites.
 */
export type ScrapeSiteIPTV = {
    type?: "iptv";
    name: string;
    url: string;
    title_filter?: TitleFilter;
};

export type ThreadHealthModel = {
    name: string;
    is_alive: boolean;
};

/**
 * Model for title filtering.
 *
 * Items in regex_postprocessing will be applied to remove parts of the title via re.sub.
 *
 * The other lists will be evaluated in order:
 * - always_exclude_words
 * - always_include_words
 * - exclude_words
 * - include_words (if populated, otherwise allow any)
 */
export type TitleFilter = {
    always_exclude_words?: Array<(string)>;
    always_include_words?: Array<(string)>;
    exclude_words?: Array<(string)>;
    include_words?: Array<(string)>;
    regex_postprocessing?: Array<(string)>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type XCCredentials = {
    username: string;
    password: string;
};

export type AcePoolPoolResponse = (AcePoolForApi);

export type AcePoolGetByContentIdData = {
    contentId: string;
};

export type AcePoolGetByContentIdResponse = (AcePoolEntryForAPI);

export type AcePoolDeleteByContentIdData = {
    contentId: string;
};

export type AcePoolDeleteByContentIdResponse = (MessageResponseModel);

export type AcePoolGetByPidData = {
    pid: string;
};

export type AcePoolGetByPidResponse = (AcePoolEntryForAPI);

export type AcePoolStatsResponse = (Array<AcePoolAllStatsApi>);

export type AcePoolStatsByContentIdData = {
    contentId: string;
};

export type AcePoolStatsByContentIdResponse = (AcePoolStat);

export type AcePoolStatsByPidData = {
    pid: string;
};

export type AcePoolStatsByPidResponse = (AcePoolStat);

export type ConfigGetConfigResponse = (ConfigExport);

export type ConfigUpdateConfigData = {
    requestBody: ConfigExport;
};

export type ConfigUpdateConfigResponse = (ConfigExport);

export type ConfigFetchRemoteSettingsResponse = (RemoteSettingsURLGetModel);

export type ConfigTriggerFetchRemoteSettingsData = {
    requestBody: RemoteSettingsURLSetModel;
};

export type ConfigTriggerFetchRemoteSettingsResponse = (MessageResponseModel);

export type ConfigReloadConfigResponse = (MessageResponseModel);

export type FrontendFrontendIndexHtmlResponse = (string);

export type FrontendFrontendIndexResponse = (string);

export type HealthHealthResponse = (HealthResponseModel);

export type MediaIptvIptvM3U83Response = (unknown);

export type MediaIptvIptvM3U2Response = (unknown);

export type MediaIptvIptvM3U81Response = (unknown);

export type ScraperSourcesResponse = (Array<AceScraperSourceApi>);

export type ScraperAddSourceData = {
    requestBody: (AceScraperSourceApi | Array<AceScraperSourceApi>);
};

export type ScraperAddSourceResponse = (MessageResponseModel);

export type ScraperSourceData = {
    sourceSlug: string;
};

export type ScraperSourceResponse = (AceScraperSourceApi);

export type ScraperUpdateSourceData = {
    requestBody: AceScraperSourceApi;
    slug: string;
};

export type ScraperUpdateSourceResponse = (MessageResponseModel);

export type ScraperRemoveSourceData = {
    slug: string;
};

export type ScraperRemoveSourceResponse = (MessageResponseModel);

export type ScraperGetNameOverridesResponse = ({
    [key: string]: (string);
});

export type ScraperDeleteNameOverrideData = {
    contentId: string;
};

export type ScraperDeleteNameOverrideResponse = (MessageResponseModel);

export type ScraperAddNameOverrideData = {
    contentId: string;
    name: string;
};

export type ScraperAddNameOverrideResponse = (MessageResponseModel);

export type StreamsByContentIdData = {
    contentId: string;
};

export type StreamsByContentIdResponse = (FoundAceStreamAPI);

export type StreamsDeleteByContentIdData = {
    contentId: string;
};

export type StreamsDeleteByContentIdResponse = (MessageResponseModel);

export type StreamsStreamsResponse = (Array<FoundAceStreamAPI>);

export type StreamsAddStreamData = {
    requestBody: ManuallyAddedAceStream;
};

export type StreamsAddStreamResponse = (MessageResponseModel);

export type StreamsCheckResponse = (MessageResponseModel);

export type XtreamCodesGetXcCredentialsResponse = (XCCredentials);

export type XtreamCodesXcIptvRouterData = {
    action?: string;
    categoryId?: string;
    password?: string;
    username?: string;
};

export type XtreamCodesXcIptvRouterResponse = (unknown);

export type XtreamCodesXcGetData = {
    password?: string;
    type?: string;
    username?: string;
};

export type XtreamCodesXcGetResponse = (unknown);