// This file is auto-generated by @hey-api/openapi-ts

/**
 * Model for all stats of AcePool instances.
 */
export type AcePoolAllStatsApi = {
    pid: number;
    status: (AcePoolStat | null);
};

/**
 * Nice model with some calculated fields for the API.
 */
export type AcePoolEntryForAPI = {
    locked_in?: boolean;
    time_until_unlock?: number;
    time_running?: number;
    ace_pid: number;
    content_id: string;
    last_used: string;
    date_started: string;
    ace_hls_m3u8_url?: (string | null);
};

/**
 * Model for the AcePool API response.
 */
export type AcePoolForApi = {
    ace_version: string;
    ace_address: (string | null);
    max_size: number;
    healthy: boolean;
    transcode_audio: boolean;
    ace_instances: Array<AcePoolEntryForAPI>;
    external_url: string;
};

/**
 * Matches the stat response from the AcePool API.
 */
export type AcePoolStat = {
    response: AcePoolStatResponse;
    error?: (string | null);
};

/**
 * Matches the response from the AcePool API.
 */
export type AcePoolStatResponse = {
    uploaded: number;
    network_monitor_status: number;
    debug_level: number;
    disk_cache_stats: AcePoolStatResponseDiskCache;
    speed_down: number;
    speed_up: number;
    network_monitor_started: boolean;
    selected_stream_index: number;
    total_progress: number;
    stream_status: number;
    client_session_id: number;
    status: string;
    downloaded: number;
    manifest_access_mode: number;
    peers: number;
    playback_session_id: string;
    is_encrypted: number;
    is_live: number;
    infohash: string;
    selected_file_index: number;
    livepos?: (AcePoolStatResponseLivePos | null);
};

/**
 * Matches the disk cache response from the AcePool API.
 */
export type AcePoolStatResponseDiskCache = {
    avail: number;
    disk_cache_limit: number;
    inactive_inuse: number;
    active_inuse: number;
};

/**
 * Matches the live position response from the AcePool API.
 */
export type AcePoolStatResponseLivePos = {
    last: number;
    live_first: number;
    pos: number;
    first_ts: number;
    last_ts: number;
    is_live: number;
    live_last: number;
    buffer_pieces: number;
};

/**
 * Settings Definition.
 */
export type AceReStreamerConf = {
    app?: AppConf;
    logging?: LoggingConf;
    scraper?: AceScrapeConf;
    epgs?: Array<EPGInstanceConf>;
    FRONTEND_HOST?: string;
    ENVIRONMENT?: 'local' | 'staging' | 'production';
    EXTERNAL_URL?: string;
    ACCESS_TOKEN_EXPIRE_MINUTES?: number;
    SECRET_KEY?: string;
    FIRST_SUPERUSER?: string;
    FIRST_SUPERUSER_PASSWORD?: string;
    BACKEND_CORS_ORIGINS?: (Array<(string)> | string);
    readonly all_cors_origins: Array<(string)>;
};

export type ENVIRONMENT = 'local' | 'staging' | 'production';

/**
 * Settings for scraping AceStreams.
 */
export type AceScrapeConf = {
    playlist_name?: string;
    adhoc_playlist_external_url?: (string | null);
    tvg_logo_external_url?: (string | null);
    html?: Array<ScrapeSiteHTML>;
    iptv_m3u8?: Array<ScrapeSiteIPTV>;
    api?: Array<ScrapeSiteAPI>;
    name_replacements?: {
        [key: string]: (string);
    };
    category_mapping?: {
        [key: string]: Array<(string)>;
    };
};

/**
 * Represent a scraper instance, generic for HTML and IPTV sources.
 */
export type AceScraperSourceApi = {
    name: string;
    url: string;
    title_filter?: TitleFilter;
    html_filter?: (HTMLScraperFilter | null);
    type: 'html' | 'iptv' | 'api';
};

export type type = 'html' | 'iptv' | 'api';

/**
 * Application configuration definition.
 */
export type AppConf = {
    authentication_enabled?: boolean;
    ace_address?: string;
    transcode_audio?: boolean;
    ace_max_streams?: number;
};

export type Body_Login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Model for EPG API handler response.
 */
export type EPGApiHandlerResponse = {
    time_until_next_update: number;
    tvg_ids: Array<(string)>;
    epgs: Array<EPGApiResponse>;
};

/**
 * Model for EPG API response.
 */
export type EPGApiResponse = {
    url: string;
    region_code: string;
    time_since_last_updated: number;
    time_until_next_update: number;
};

/**
 * EPG (Electronic Program Guide) configuration definition.
 */
export type EPGInstanceConf = {
    region_code?: string;
    format?: string;
    url?: string;
};

export type ErrorDetails = {
    type: string;
    loc: Array<(number | string)>;
    msg: string;
    input: unknown;
    ctx?: {
        [key: string]: unknown;
    };
    url?: string;
};

/**
 * Flat model for a found AceStream.
 */
export type FoundAceStreamAPI = {
    site_names: Array<(string)>;
    quality: number;
    title: string;
    content_id: string;
    infohash: string;
    tvg_id: string;
    tvg_logo?: (string | null);
    program_title?: string;
    program_description?: string;
    has_ever_worked: boolean;
};

export type HealthResponseModel = {
    version: string;
    version_full: string;
    time_zone: string;
    threads: Array<ThreadHealthModel>;
    memory_usage_mb: string;
};

/**
 * Model for HTML scraper filtering.
 */
export type HTMLScraperFilter = {
    target_class?: string;
    check_sibling?: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Logging configuration definition.
 */
export type LoggingConf = {
    level?: (string | number);
    path?: (string | null);
    simple?: boolean;
};

export type Message = {
    message: string;
};

/**
 * Generic API response message model.
 */
export type MessageResponseModel = {
    message: string;
    errors?: (Array<(string)> | Array<ErrorDetails> | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    username: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Model for tracking quality of a stream.
 */
export type Quality = {
    quality?: number;
    has_ever_worked?: boolean;
    m3u_failures?: number;
};

/**
 * Scraper for API Sites.
 */
export type ScrapeSiteAPI = {
    type?: "api";
    name: string;
    url: string;
    title_filter?: TitleFilter;
};

/**
 * Model for a site to scrape.
 */
export type ScrapeSiteHTML = {
    type?: "html";
    name: string;
    url: string;
    title_filter?: TitleFilter;
    html_filter?: HTMLScraperFilter;
};

/**
 * Scraper for IPTV Sites.
 */
export type ScrapeSiteIPTV = {
    type?: "iptv";
    name: string;
    url: string;
    title_filter?: TitleFilter;
};

export type StreamToken = {
    stream_token: string;
};

export type ThreadHealthModel = {
    name: string;
    is_alive: boolean;
};

/**
 * Model for title filtering.
 */
export type TitleFilter = {
    always_exclude_words?: Array<(string)>;
    always_include_words?: Array<(string)>;
    exclude_words?: Array<(string)>;
    include_words?: Array<(string)>;
    regex_postprocessing?: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    stream_token?: string;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    stream_token?: string;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    username: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    username?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    stream_token?: string;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    username?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AcePoolPoolResponse = (AcePoolForApi);

export type AcePoolGetByContentIdData = {
    contentId: string;
};

export type AcePoolGetByContentIdResponse = (AcePoolEntryForAPI);

export type AcePoolDeleteByContentIdData = {
    contentId: string;
};

export type AcePoolDeleteByContentIdResponse = (MessageResponseModel);

export type AcePoolGetByPidData = {
    pid: string;
};

export type AcePoolGetByPidResponse = (AcePoolEntryForAPI);

export type AcePoolStatsResponse = (AcePoolAllStatsApi);

export type AcePoolStatsByContentIdData = {
    contentId: string;
};

export type AcePoolStatsByContentIdResponse = (AcePoolStat);

export type AcePoolStatsByPidData = {
    pid: string;
};

export type AcePoolStatsByPidResponse = (AcePoolStat);

export type ConfigurationGetConfigResponse = (AceReStreamerConf);

export type ConfigurationLoadConfigData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type ConfigurationLoadConfigResponse = (MessageResponseModel);

export type EpgEpgsResponse = (EPGApiHandlerResponse);

export type FrontendFrontendIndexHtmlResponse = (string);

export type FrontendFrontendIndexResponse = (string);

export type HealthHealthResponse = (HealthResponseModel);

export type LoginLoginAccessTokenData = {
    formData: Body_Login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type MediaIptvIptvM3U83Data = {
    token?: string;
};

export type MediaIptvIptvM3U83Response = (unknown);

export type MediaIptvIptvM3U2Data = {
    token?: string;
};

export type MediaIptvIptvM3U2Response = (unknown);

export type MediaIptvIptvM3U81Data = {
    token?: string;
};

export type MediaIptvIptvM3U81Response = (unknown);

export type MediaStreamHlsData = {
    authenticationOverride?: boolean;
    path: string;
    token?: string;
};

export type MediaStreamHlsResponse = (unknown);

export type MediaStreamHlsMultiData = {
    path: string;
    token?: string;
};

export type MediaStreamHlsMultiResponse = (unknown);

export type MediaStreamXcM3U8Data = {
    password: string;
    password?: string;
    path: string;
    username: string;
    username?: string;
};

export type MediaStreamXcM3U8Response = (unknown);

export type MediaStreamAceContent2Data = {
    path: string;
    token?: string;
};

export type MediaStreamAceContent2Response = (unknown);

export type MediaStreamAceContent1Data = {
    path: string;
    token?: string;
};

export type MediaStreamAceContent1Response = (unknown);

export type MediaStreamTvgLogoData = {
    path: string;
    token?: string;
};

export type MediaStreamTvgLogoResponse = (unknown);

export type MediaXmlEpgXml2Data = {
    token?: string;
};

export type MediaXmlEpgXml2Response = (unknown);

export type MediaXmlEpgXml1Data = {
    token?: string;
};

export type MediaXmlEpgXml1Response = (unknown);

export type MediaXmlEpgXml3Data = {
    password?: string;
    username?: string;
};

export type MediaXmlEpgXml3Response = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ScraperSourcesResponse = (Array<AceScraperSourceApi>);

export type ScraperAddSourceData = {
    requestBody: (AceScraperSourceApi | Array<AceScraperSourceApi>);
};

export type ScraperAddSourceResponse = (MessageResponseModel);

export type ScraperSourceData = {
    sourceSlug: string;
};

export type ScraperSourceResponse = (AceScraperSourceApi);

export type ScraperRemoveSourceData = {
    slug: string;
};

export type ScraperRemoveSourceResponse = (MessageResponseModel);

export type ScraperCheckResponse = (MessageResponseModel);

export type StreamsByContentIdData = {
    contentId: string;
};

export type StreamsByContentIdResponse = (FoundAceStreamAPI);

export type StreamsStreamsResponse = (Array<FoundAceStreamAPI>);

export type StreamsHealthResponse = ({
    [key: string]: Quality;
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadStreamTokenMeResponse = (StreamToken);

export type UsersRegenerateStreamTokenMeResponse = (StreamToken);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type XtreamCodesXcIptvRouterData = {
    action?: string;
    categoryId?: string;
    password?: string;
    username?: string;
};

export type XtreamCodesXcIptvRouterResponse = (unknown);

export type XtreamCodesXcGetData = {
    password?: string;
    type?: string;
    username?: string;
};

export type XtreamCodesXcGetResponse = (unknown);