// This file is auto-generated by @hey-api/openapi-ts

/**
 * Model for all stats of AcePool instances.
 */
export type AcePoolAllStatsApi = {
    pid: number;
    status: (AcePoolStat | null);
};

/**
 * Nice model with some calculated fields for the API.
 */
export type AcePoolEntryForAPI = {
    locked_in?: boolean;
    time_until_unlock?: number;
    time_running?: number;
    ace_pid: number;
    content_id: string;
    last_used: string;
    date_started: string;
    ace_hls_m3u8_url?: (string | null);
};

/**
 * Model for the AcePool API response.
 */
export type AcePoolForApi = {
    ace_version: (AceVersionResult | null);
    ace_address: (string | null);
    max_size: number;
    healthy: boolean;
    transcode_audio: boolean;
    ace_instances: Array<AcePoolEntryForAPI>;
    external_url: string;
};

/**
 * Matches the stat response from the AcePool API.
 */
export type AcePoolStat = {
    response: AcePoolStatResponse;
    error?: (string | null);
};

/**
 * Matches the response from the AcePool API.
 */
export type AcePoolStatResponse = {
    uploaded: number;
    network_monitor_status: number;
    debug_level: number;
    disk_cache_stats: AcePoolStatResponseDiskCache;
    speed_down: number;
    speed_up: number;
    network_monitor_started: boolean;
    selected_stream_index: number;
    total_progress: number;
    stream_status: number;
    client_session_id: number;
    status: string;
    downloaded: number;
    manifest_access_mode: number;
    peers: number;
    playback_session_id: string;
    is_encrypted: number;
    is_live: number;
    infohash: string;
    selected_file_index: number;
    livepos?: (AcePoolStatResponseLivePos | null);
};

/**
 * Matches the disk cache response from the AcePool API.
 */
export type AcePoolStatResponseDiskCache = {
    avail: number;
    disk_cache_limit: number;
    inactive_inuse: number;
    active_inuse: number;
};

/**
 * Matches the live position response from the AcePool API.
 */
export type AcePoolStatResponseLivePos = {
    last: number;
    live_first: number;
    pos: number;
    first_ts: number;
    last_ts: number;
    is_live: number;
    live_last: number;
    buffer_pieces: number;
};

/**
 * Settings for scraping AceStreams.
 */
export type AceScrapeConf_Input = {
    playlist_name?: string;
    adhoc_playlist_external_url?: (string | null);
    tvg_logo_external_url?: (string | null);
    html?: Array<ScrapeSiteHTML>;
    iptv_m3u8?: Array<ScrapeSiteIPTV>;
    api?: Array<ScrapeSiteAPI>;
    content_id_infohash_name_overrides?: {
        [key: string]: (string);
    };
    category_mapping?: {
        [key: string]: Array<(string)>;
    };
};

/**
 * Settings for scraping AceStreams.
 */
export type AceScrapeConf_Output = {
    playlist_name?: string;
    adhoc_playlist_external_url?: (string | null);
    tvg_logo_external_url?: (string | null);
    html?: Array<ScrapeSiteHTML>;
    iptv_m3u8?: Array<ScrapeSiteIPTV>;
    api?: Array<ScrapeSiteAPI>;
    content_id_infohash_name_overrides?: {
        [key: string]: (string);
    };
    category_mapping?: {
        [key: string]: Array<(string)>;
    };
};

/**
 * Represent a scraper instance, generic for HTML and IPTV sources.
 */
export type AceScraperSourceApi = {
    name: string;
    url: string;
    title_filter?: TitleFilter;
    html_filter?: (HTMLScraperFilter | null);
    type: 'html' | 'iptv' | 'api';
};

export type type = 'html' | 'iptv' | 'api';

export type AceVersionResult = {
    code: number;
    version: string;
    platform: 'win32' | 'linux' | 'android';
};

export type platform = 'win32' | 'linux' | 'android';

export type Body_Login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Unified stream model combining ace and IPTV streams, for API use.
 */
export type CombinedStreamAPI = {
    stream_type: 'ace' | 'iptv';
    title: string;
    stream_url: string;
    tvg_id: string;
    tvg_logo?: (string | null);
    group_title: string;
    last_scraped_time: string;
    program_title: string;
    program_description: string;
    quality: number;
};

export type stream_type = 'ace' | 'iptv';

/**
 * Export model for scraper and EPG configuration only.
 */
export type ConfigExport_Input = {
    scraper: AceScrapeConf_Input;
    epgs: Array<EPGInstanceConf_Input>;
};

/**
 * Export model for scraper and EPG configuration only.
 */
export type ConfigExport_Output = {
    scraper: AceScrapeConf_Output;
    epgs: Array<EPGInstanceConf_Output>;
};

/**
 * Model for EPG API handler response.
 */
export type EPGApiHandlerHealthResponse = {
    time_until_next_update: number;
    tvg_ids: Array<(string)>;
    epgs: {
        [key: string]: EPGApiHealthResponse;
    };
};

/**
 * Model for EPG API response.
 */
export type EPGApiHealthResponse = {
    time_since_last_updated: number;
    time_until_next_update: number;
};

/**
 * EPG (Electronic Program Guide) configuration definition.
 *
 * tvg_id_overrides is a str:str dict where you can override stream tvg_ids to match those in the EPG.
 */
export type EPGInstanceConf_Input = {
    format?: 'xml.gz' | 'xml';
    url: string;
    tvg_id_overrides?: {
        [key: string]: (string);
    };
};

export type format = 'xml.gz' | 'xml';

/**
 * EPG (Electronic Program Guide) configuration definition.
 *
 * tvg_id_overrides is a str:str dict where you can override stream tvg_ids to match those in the EPG.
 */
export type EPGInstanceConf_Output = {
    format?: 'xml.gz' | 'xml';
    url: string;
    tvg_id_overrides?: {
        [key: string]: (string);
    };
    /**
     * Generate a slug from the url.
     */
    readonly slug: string;
};

export type ErrorDetails = {
    type: string;
    loc: Array<(number | string)>;
    msg: string;
    input: unknown;
    ctx?: {
        [key: string]: unknown;
    };
    url?: string;
};

/**
 * Model for a found AceStream.
 */
export type FoundAceStreamAPI = {
    title: string;
    content_id: string;
    infohash?: (string | null);
    tvg_id: string;
    tvg_logo?: (string | null);
    last_scraped_time: string;
    program_title: string;
    program_description: string;
    quality: number;
    has_ever_worked: boolean;
    m3u_failures: number;
};

/**
 * Model for an IPTV proxy stream, for API use.
 */
export type FoundIPTVStreamAPI = {
    title: string;
    original_title: string;
    slug: string;
    upstream_url: string;
    source_name: string;
    tvg_id: string;
    tvg_logo?: (string | null);
    group_title: string;
    last_scraped_time: string;
    program_title: string;
    program_description: string;
    quality: number;
    has_ever_worked: boolean;
    m3u_failures: number;
};

export type HealthResponseModel = {
    version: string;
    version_full: string;
    time_zone: string;
    threads: Array<ThreadHealthModel>;
    memory_usage_mb: string;
};

/**
 * Model for HTML scraper filtering.
 */
export type HTMLScraperFilter = {
    target_class?: string;
    check_sibling?: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * API representation of a single IPTV pool entry.
 */
export type IPTVPoolEntryForAPI = {
    slug: string;
    source_name: string;
    date_started: string;
    last_used: string;
    locked_in: boolean;
    time_until_unlock_seconds: number;
    time_running_seconds: number;
};

/**
 * API representation of all IPTV source pools.
 */
export type IPTVPoolForAPI = {
    sources: Array<IPTVPoolSourceForAPI>;
};

/**
 * API representation of a single source's pool.
 */
export type IPTVPoolSourceForAPI = {
    source_name: string;
    max_size: number;
    entries: Array<IPTVPoolEntryForAPI>;
    /**
     * Number of active entries.
     */
    readonly active_count: number;
};

/**
 * Represent an IPTV proxy source, generic for Xtream and M3U8 sources.
 */
export type IPTVSourceApi = {
    name: string;
    url: string;
    type: 'xtream' | 'm3u8';
    title_filter?: TitleFilter;
    category_filter?: TitleFilter;
    max_active_streams?: number;
    username?: (string | null);
    password?: (string | null);
    use_epg?: (boolean | null);
};

export type type2 = 'xtream' | 'm3u8';

/**
 * Override scraped metadata for a specific IPTV stream by title.
 */
export type IPTVStreamOverride = {
    name?: string;
    category?: string;
    tvg_id?: string;
};

/**
 * Model for a manually added AceStream.
 */
export type ManuallyAddedAceStream = {
    title: string;
    content_id: string;
    group_title: string;
};

export type Message = {
    message: string;
};

/**
 * Generic API response message model.
 */
export type MessageResponseModel = {
    message: string;
    errors?: (Array<(string)> | Array<ErrorDetails> | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    username: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RemoteSettingsGetModel = {
    url: (string | null);
    enable_epg: boolean;
    enable_ace: boolean;
    status: string;
    last_fetched: (string | null);
};

export type RemoteSettingsSetModel = {
    url: (string | null);
    enable_epg?: boolean;
    enable_ace?: boolean;
};

/**
 * Scraper for API Sites.
 */
export type ScrapeSiteAPI = {
    type?: "api";
    name: string;
    url: string;
    title_filter?: TitleFilter;
};

/**
 * Model for a site to scrape.
 */
export type ScrapeSiteHTML = {
    type?: "html";
    name: string;
    url: string;
    title_filter?: TitleFilter;
    html_filter?: HTMLScraperFilter;
};

/**
 * Scraper for IPTV Sites.
 */
export type ScrapeSiteIPTV = {
    type?: "iptv";
    name: string;
    url: string;
    title_filter?: TitleFilter;
};

export type StreamToken = {
    stream_token: string;
};

export type ThreadHealthModel = {
    name: string;
    is_alive: boolean;
};

/**
 * Model for title filtering.
 *
 * Items in regex_postprocessing will be applied to remove parts of the title via re.sub.
 *
 * The other lists will be evaluated in order:
 * - always_exclude_words
 * - always_include_words
 * - exclude_words
 * - include_words (if populated, otherwise allow any)
 */
export type TitleFilter = {
    always_exclude_words?: Array<(string)>;
    always_include_words?: Array<(string)>;
    exclude_words?: Array<(string)>;
    include_words?: Array<(string)>;
    regex_postprocessing?: Array<(string)>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Model for TVG EPG mappings response.
 */
export type TVGEPGMappingsResponse = {
    [key: string]: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    stream_token?: string;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    stream_token?: string;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    username: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    username?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    stream_token?: string;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    username?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AcePoolPoolResponse = (AcePoolForApi);

export type AcePoolGetByContentIdData = {
    contentId: string;
};

export type AcePoolGetByContentIdResponse = (AcePoolEntryForAPI);

export type AcePoolDeleteByContentIdData = {
    contentId: string;
};

export type AcePoolDeleteByContentIdResponse = (MessageResponseModel);

export type AcePoolGetByPidData = {
    pid: string;
};

export type AcePoolGetByPidResponse = (AcePoolEntryForAPI);

export type AcePoolStatsResponse = (Array<AcePoolAllStatsApi>);

export type AcePoolStatsByContentIdData = {
    contentId: string;
};

export type AcePoolStatsByContentIdResponse = (AcePoolStat);

export type AcePoolStatsByPidData = {
    pid: string;
};

export type AcePoolStatsByPidResponse = (AcePoolStat);

export type AceScraperSourcesResponse = (Array<AceScraperSourceApi>);

export type AceScraperAddSourceData = {
    requestBody: (AceScraperSourceApi | Array<AceScraperSourceApi>);
};

export type AceScraperAddSourceResponse = (MessageResponseModel);

export type AceScraperSourceData = {
    sourceSlug: string;
};

export type AceScraperSourceResponse = (AceScraperSourceApi);

export type AceScraperRemoveSourceData = {
    slug: string;
};

export type AceScraperRemoveSourceResponse = (MessageResponseModel);

export type AceScraperGetNameOverridesResponse = ({
    [key: string]: (string);
});

export type AceScraperDeleteNameOverrideData = {
    contentId: string;
};

export type AceScraperDeleteNameOverrideResponse = (MessageResponseModel);

export type AceScraperAddNameOverrideData = {
    contentId: string;
    name: string;
};

export type AceScraperAddNameOverrideResponse = (MessageResponseModel);

export type AceStreamsByContentIdData = {
    contentId: string;
};

export type AceStreamsByContentIdResponse = (FoundAceStreamAPI);

export type AceStreamsDeleteByContentIdData = {
    contentId: string;
};

export type AceStreamsDeleteByContentIdResponse = (MessageResponseModel);

export type AceStreamsStreamsResponse = (Array<FoundAceStreamAPI>);

export type AceStreamsAddStreamData = {
    requestBody: ManuallyAddedAceStream;
};

export type AceStreamsAddStreamResponse = (MessageResponseModel);

export type AceStreamsCheckResponse = (MessageResponseModel);

export type ConfigGetConfigResponse = (ConfigExport_Output);

export type ConfigUpdateConfigData = {
    requestBody: ConfigExport_Input;
};

export type ConfigUpdateConfigResponse = (ConfigExport_Output);

export type ConfigFetchRemoteSettingsResponse = (RemoteSettingsGetModel);

export type ConfigTriggerFetchRemoteSettingsData = {
    requestBody: RemoteSettingsSetModel;
};

export type ConfigTriggerFetchRemoteSettingsResponse = (MessageResponseModel);

export type ConfigReloadConfigResponse = (MessageResponseModel);

export type EpgEpgHealthResponse = (EPGApiHandlerHealthResponse);

export type EpgGetEpgsResponse = (Array<EPGInstanceConf_Output>);

export type EpgAddEpgData = {
    requestBody: (EPGInstanceConf_Input | Array<EPGInstanceConf_Input>);
};

export type EpgAddEpgResponse = (unknown);

export type EpgModifyEpgData = {
    requestBody: (EPGInstanceConf_Input | Array<EPGInstanceConf_Input>);
};

export type EpgModifyEpgResponse = (unknown);

export type EpgGetEpgData = {
    slug: string;
};

export type EpgGetEpgResponse = (EPGInstanceConf_Output);

export type EpgDeleteEpgData = {
    slug: string;
};

export type EpgDeleteEpgResponse = (unknown);

export type EpgTvgEpgMappingsResponse = (TVGEPGMappingsResponse);

export type FrontendFrontendIndexHtmlResponse = (string);

export type FrontendFrontendIndexResponse = (string);

export type HealthHealthResponse = (HealthResponseModel);

export type IptvPoolPoolResponse = (IPTVPoolForAPI);

export type IptvPoolPoolBySourceData = {
    sourceName: string;
};

export type IptvPoolPoolBySourceResponse = (IPTVPoolSourceForAPI);

export type IptvPoolDeleteEntryData = {
    slug: string;
    sourceName: string;
};

export type IptvPoolDeleteEntryResponse = (MessageResponseModel);

export type IptvScraperSourcesResponse = (Array<IPTVSourceApi>);

export type IptvScraperAddSourceData = {
    requestBody: (IPTVSourceApi | Array<IPTVSourceApi>);
};

export type IptvScraperAddSourceResponse = (MessageResponseModel);

export type IptvScraperSourceData = {
    sourceName: string;
};

export type IptvScraperSourceResponse = (IPTVSourceApi);

export type IptvScraperRemoveSourceData = {
    sourceName: string;
};

export type IptvScraperRemoveSourceResponse = (MessageResponseModel);

export type IptvScraperGetStreamOverridesData = {
    sourceName: string;
};

export type IptvScraperGetStreamOverridesResponse = ({
    [key: string]: IPTVStreamOverride;
});

export type IptvScraperSetStreamOverrideData = {
    requestBody: IPTVStreamOverride;
    sourceName: string;
    streamTitle: string;
};

export type IptvScraperSetStreamOverrideResponse = (MessageResponseModel);

export type IptvScraperDeleteStreamOverrideData = {
    sourceName: string;
    streamTitle: string;
};

export type IptvScraperDeleteStreamOverrideResponse = (MessageResponseModel);

export type IptvStreamsStreamsResponse = (Array<FoundIPTVStreamAPI>);

export type IptvStreamsBySlugData = {
    slug: string;
};

export type IptvStreamsBySlugResponse = (FoundIPTVStreamAPI);

export type IptvStreamsDeleteBySlugData = {
    slug: string;
};

export type IptvStreamsDeleteBySlugResponse = (MessageResponseModel);

export type LoginLoginAccessTokenData = {
    formData: Body_Login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type MediaIptvIptvM3U83Data = {
    token?: string;
};

export type MediaIptvIptvM3U83Response = (unknown);

export type MediaIptvIptvM3U2Data = {
    token?: string;
};

export type MediaIptvIptvM3U2Response = (unknown);

export type MediaIptvIptvM3U81Data = {
    token?: string;
};

export type MediaIptvIptvM3U81Response = (unknown);

export type MediaXmlEpgXmlData = {
    token?: string;
};

export type MediaXmlEpgXmlResponse = (unknown);

export type MediaXmlEpgXml3Data = {
    password?: string;
    username?: string;
};

export type MediaXmlEpgXml3Response = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type StreamsStreamsResponse = (Array<CombinedStreamAPI>);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadStreamTokenMeResponse = (StreamToken);

export type UsersRegenerateStreamTokenMeResponse = (StreamToken);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type XtreamCodesXcIptvRouterData = {
    action?: string;
    categoryId?: string;
    password?: string;
    username?: string;
};

export type XtreamCodesXcIptvRouterResponse = (unknown);

export type XtreamCodesXcGetData = {
    password?: string;
    type?: string;
    username?: string;
};

export type XtreamCodesXcGetResponse = (unknown);