/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSystemRouteImport } from './routes/_layout/system'
import { Route as LayoutScrapersRouteImport } from './routes/_layout/scrapers'
import { Route as LayoutChannelsRouteImport } from './routes/_layout/channels'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemRoute = LayoutSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScrapersRoute = LayoutScrapersRouteImport.update({
  id: '/scrapers',
  path: '/scrapers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChannelsRoute = LayoutChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/channels': typeof LayoutChannelsRoute
  '/scrapers': typeof LayoutScrapersRoute
  '/system': typeof LayoutSystemRoute
}
export interface FileRoutesByTo {
  '/channels': typeof LayoutChannelsRoute
  '/scrapers': typeof LayoutScrapersRoute
  '/system': typeof LayoutSystemRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/channels': typeof LayoutChannelsRoute
  '/_layout/scrapers': typeof LayoutScrapersRoute
  '/_layout/system': typeof LayoutSystemRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/channels' | '/scrapers' | '/system'
  fileRoutesByTo: FileRoutesByTo
  to: '/channels' | '/scrapers' | '/system' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/channels'
    | '/_layout/scrapers'
    | '/_layout/system'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system': {
      id: '/_layout/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof LayoutSystemRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scrapers': {
      id: '/_layout/scrapers'
      path: '/scrapers'
      fullPath: '/scrapers'
      preLoaderRoute: typeof LayoutScrapersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/channels': {
      id: '/_layout/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof LayoutChannelsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutChannelsRoute: typeof LayoutChannelsRoute
  LayoutScrapersRoute: typeof LayoutScrapersRoute
  LayoutSystemRoute: typeof LayoutSystemRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutChannelsRoute: LayoutChannelsRoute,
  LayoutScrapersRoute: LayoutScrapersRoute,
  LayoutSystemRoute: LayoutSystemRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
